config/routes.rb
require 'caffeine/constraints/page_constraint'

module Caffeine
  Engine.routes.draw do
    devise_for :admin_users, class_name: 'Caffeine::AdminUser', module: :devise

    root 'main_page#index'

    authenticate :admin_user do
      namespace :admin do
        root 'dashboard#index'

        get 'pages/search', to: 'pages#search'

        resources :pages
        resources :pictures, only: [:create, :destroy]
      end
    end

    # Define route for page tags
    get '*page_id/tags/:id', controller: 'pages/tags', action: :show, as: :page_tag

    # Define route for pages
    get '*page_id', to: 'pages#show', constraints: PageConstraint, as: :page
    end
end

app/views/caffeine/admin/partials/_header.html.slim
header.header.clearfix
  .header__fill
    .header__logo
      .logo.logo--small
        = link_to '', admin_root_path
    .header__tray
      .header__tray__profile
        span.favicon
          = image_tag favicon_path, title: app_name
        span.more
          = t('caffeine.admin.partials.header.welcome')
          span.admin= t('.admin')
        = link_to '/admin/sign_out', class: 'sign-out', title: t('.sign_out')
          = image_tag 'caffeine/admin/svg/logout.svg', class: 'svg'
    .header__page-title
      span= content_for :header_page_title
  .splash-block

app/views/caffeine/admin/partials/_sidebar.html.slim
aside.sidebar__pages
  = render 'caffeine/admin/partials/modules/nav_pages'
aside.sidebar__components
  = render 'caffeine/admin/partials/modules/nav_components'
aside.sidebar__statistics
  = render 'caffeine/admin/partials/modules/statistics'