config/routes.rb
require 'caffeine/constraints/page_constraint'

module Caffeine
  Engine.routes.draw do
    devise_for :admin_users, class_name: 'Caffeine::AdminUser', module: :devise

    root 'main_page#index'

    authenticate :admin_user do
      namespace :admin do
        root 'dashboard#index'

        get 'pages/search', to: 'pages#search'

        resources :pages
        resources :pictures, only: [:create, :destroy]
      end
    end

    # Define route for page tags
    get '*page_id/tags/:id', controller: 'pages/tags', action: :show, as: :page_tag

    # Define route for pages
    get '*page_id', to: 'pages#show', constraints: PageConstraint, as: :page
    end
end

app/views/caffeine/admin/partials/modules/_item.html.slim
span.nav__item--fill
  a.title href='#'
    i.fa.fa-file-text-o
    = page.title
    - if page.children.any?
      span.count-children
        = page.children.count
  - if page.children.any?
    span.more-children.action
      span.action__icon
        i.iconsfont.iconsfont-plus
  = render partial: 'caffeine/admin/partials/modules/page_actions', object: page, as: :page

app/views/caffeine/admin/partials/modules/_nav_components.html.slim
.module.module--components
  .module__title
    span Выберите компонент для работы ниже
  .module__content
    nav.nav.nav--components
      ul.nav__list
        li.nav__item.nav__item--settings
          span.nav__item--fill
            a.title href='#'
              | Настройки
        li.nav__item.nav__item--statistics
          span.nav__item--fill
            a.title href='#'
              | Статистика
        li.nav__item.nav__item--pages
          span.nav__item--fill
            a.title href='#'
              | Страницы
        li.nav__item.nav__item--forms
          span.nav__item--fill
            a.title href='#'
              | Формы
        li.nav__item.nav__item--access
          span.nav__item--fill
            a.title href='#'
              | Доступ
        li.nav__item.nav__item--portfolio
          span.nav__item--fill
            a.title href='#'
              | Портфолио
        li.nav__item.nav__item--seo
          span.nav__item--fill
            a.title href='#'
              | SEO
        li.nav__item.nav__item--drafts
          span.nav__item--fill
            a.title href='#'
              | Черновики

app/views/caffeine/admin/partials/modules/_nav_pages.html.slim
.module.module--pages
  .module__title
    span= app_name
    = link_to '', '#', title: t('.settings_site'), class: 'icon iconsfont iconsfont-settings'
  .module__content
    nav.nav.nav--pages
      ul.nav__list
        - root_pages.each do |page|
          = render 'caffeine/admin/partials/modules/nav_pages/item', page: page
    .buttons
      = link_to new_admin_page_path, class: 'button button--default'
        i.iconsfont.iconsfont-add-button
        span=t('.add_page')

app/views/caffeine/admin/partials/modules/_or.html.slim
.module.module--or
  .module__content
    .or= t('.text')

app/views/caffeine/admin/partials/modules/_page_actions.html.slim
span.actions
  = link_to edit_admin_page_path(page), class: ' action edit'
    span.action__icon
      i.fa.fa-pencil
    span.action__name Редактировать
  = link_to admin_page_path(page), class: 'action view'
    span.action__icon
      i.fa.fa-eye
    span.action__name Выключить
  = link_to admin_page_path(page),method: :delete,
            class: ' action delete', data: { confirm: 'Are you sure?' }
    span.action__icon
      i.fa.fa-times
    span.action__name Удалить

app/views/caffeine/admin/partials/modules/_search.html.slim
.module.module--search
  .module__content
    .search
      form.form.search__form action='#' autocomplete='off'
        .form__fill
          input#search_text.string.required name="search" placeholder="Начните вводить название страницы" type="text"
          span.button Искать
      .search__result
        .search__result__fill
          ol.search__result__list

app/views/caffeine/admin/partials/modules/_statistics.html.slim
.module.module--statistics
  .module__content